import { useEffect, useMemo, useState, type CSSProperties } from "react";
import { RocketBuilder } from "./RocketBuilder";
import { applyRocketPart, availableParts, FLIGHT_SUMMARY, makeFlightMission, missionComplete, readinessScore, ROCKET_PARTS, STAT_INFO, WORLDS, type AgePath, type FlightStats, type RocketPart } from "./flight-data";
import { speakFriendly, stopNarration } from "./narrator";

type Screen="home"|"map"|"tutorial"|"mission"|"result"|"guide"|"grownup";
type Save={age:AgePath|null;progress:Record<AgePath,number>;stars:Record<string,number>;xp:number;badges:string[]};
type Turn={stats:FlightStats;energy:number;part:RocketPart};
const SAVE_KEY="spaceflight-academy-save-v1",DEFAULT_SAVE:Save={age:null,progress:{"5–7":1,"8–10":1,"11–12":1},stars:{},xp:0,badges:[]};
const AGES=[
  {age:"5–7" as AgePath,name:"Rocket Rookie",icon:"🚀",color:"#ffd95a",detail:"Pushes and pulls, engines, fuel, fins, parachutes, communication, and simple mission goals"},
  {age:"8–10" as AgePath,name:"Orbit Cadet",icon:"🌍",color:"#62e8ff",detail:"Gravity, speed, orbit, solar power, heat protection, navigation, and system tradeoffs"},
  {age:"11–12" as AgePath,name:"Mission Engineer",icon:"🪐",color:"#d579ff",detail:"Staging, mass, life support, landing, deep-space communication, payloads, and planetary science"},
];
const TUTORIAL=[
  ["1","READ THE MISSION","Check the destination, objective, focus meter, readiness goal, and build energy."],
  ["2","ASSEMBLE THE ROCKET","Tap systems to add them to the vehicle. Every choice changes mission readiness."],
  ["3","BALANCE THE SYSTEMS","A powerful rocket also needs fuel, control, protection, navigation, and useful equipment."],
  ["4","TEST BEFORE LAUNCH","Undo one system or reset the entire rocket freely. Failed plans never remove progress."],
  ["5","REACH FLIGHT READY","Meet the focus and total readiness goals, then start the animated countdown."],
] as const;
function loadSave():Save{try{const raw=JSON.parse(localStorage.getItem(SAVE_KEY)||"{}");return{...DEFAULT_SAVE,...raw,progress:{...DEFAULT_SAVE.progress,...raw.progress},stars:{...DEFAULT_SAVE.stars,...raw.stars},badges:Array.isArray(raw.badges)?raw.badges:[]}}catch{return DEFAULT_SAVE}}
const missionKey=(age:AgePath,level:number)=>age+"-"+level;
function Topbar({save,setScreen}:{save:Save;setScreen:(screen:Screen)=>void}){const stars=Object.values(save.stars).reduce((sum,value)=>sum+value,0);return <header className="topbar"><button className="brand" onClick={()=>setScreen("home")}><span>🚀</span><b>SPACEFLIGHT</b><em>ACADEMY</em></button><div className="top-stats"><span>★ {stars}</span><span>🚀 {save.xp} XP</span><span>🏅 {save.badges.length}</span></div></header>}

export default function App(){
  const [save,setSave]=useState<Save>(loadSave),[screen,setScreen]=useState<Screen>("home"),[level,setLevel]=useState(1),[tutorial,setTutorial]=useState(0);
  const [stats,setStats]=useState<FlightStats>({thrust:0,fuel:0,stability:0,mission:0}),[energy,setEnergy]=useState(0),[history,setHistory]=useState<Turn[]>([]),[message,setMessage]=useState(""),[earned,setEarned]=useState({stars:0,xp:0}),[launching,setLaunching]=useState(false);
  const age=save.age??"5–7",mission=useMemo(()=>makeFlightMission(age,level),[age,level]),parts=availableParts(age),ready=missionComplete(mission,stats),totalStars=Object.values(save.stars).reduce((sum,value)=>sum+value,0);
  useEffect(()=>{localStorage.setItem(SAVE_KEY,JSON.stringify(save))},[save]);useEffect(()=>()=>stopNarration(),[]);
  const begin=(selected:number)=>{if(selected>save.progress[age])return;const next=makeFlightMission(age,selected);setLevel(selected);setStats(next.start);setEnergy(next.energy);setHistory([]);setMessage("");setLaunching(false);setTutorial(0);setScreen("tutorial")};
  const addPart=(part:RocketPart)=>{if(part.cost>energy||ready||launching)return;setHistory(current=>[...current,{stats,energy,part}]);setStats(current=>applyRocketPart(current,part));setEnergy(value=>value-part.cost);setMessage(part.fact);speakFriendly(part.name+". "+part.fact,age==="5–7"?.68:age==="8–10"?.72:.76)};
  const undo=()=>{const previous=history.at(-1);if(!previous||launching)return;setStats(previous.stats);setEnergy(previous.energy);setHistory(current=>current.slice(0,-1));setMessage("Last system returned to the assembly rack.")};
  const reset=()=>{if(launching)return;setStats(mission.start);setEnergy(mission.energy);setHistory([]);setMessage("Rocket reset. Try another mission plan—there is no penalty.")};
  const awardMission=()=>{const stars=energy>=5?3:energy>=2?2:1,xp=180+level*14+stars*36,badge=mission.world.name+" Pilot";setEarned({stars,xp});setSave(current=>({...current,progress:{...current.progress,[age]:Math.max(current.progress[age],Math.min(30,level+1))},stars:{...current.stars,[missionKey(age,level)]:Math.max(current.stars[missionKey(age,level)]||0,stars)},xp:current.xp+xp,badges:[...new Set([...current.badges,...(level%5===0?[badge]:[])])]}));setScreen("result");setLaunching(false)};
  const launch=()=>{if(!ready||launching)return;setLaunching(true);speakFriendly("Three, two, one. Liftoff! "+mission.objective+". Mission systems are ready.",.68);window.setTimeout(awardMission,1800)};

  if(!save.age)return <main className="onboarding space-onboarding"><section><div className="eco-logo">🚀<i>🌍</i><i>🪐</i></div><p className="eyebrow">FLEXZONIC ORBITAL LEARNING COMMAND</p><h1>SPACEFLIGHT<br/><em>ACADEMY</em></h1><p>Build, launch, and explore through colorful space missions about forces, gravity, energy, navigation, engineering, and planetary science.</p><div className="age-grid">{AGES.map(item=><button key={item.age} style={{"--accent":item.color} as CSSProperties} onClick={()=>setSave(current=>({...current,age:item.age}))}><span>{item.icon}</span><small>AGES {item.age}</small><b>{item.name}</b><p>{item.detail}</p></button>)}</div></section></main>;
  if(screen==="tutorial"){const step=TUTORIAL[tutorial];return <><Topbar save={save} setScreen={setScreen}/><main className="modal-screen"><section className="modal"><div className="steps">{TUTORIAL.map((_,i)=><i key={i} className={i<=tutorial?"on":""}/>)}</div><div className="tutorial-icon">{step[0]}</div><p className="eyebrow">CADET TRAINING {tutorial+1}/5</p><h2>{step[1]}</h2><p>{step[2]}</p><div className="mission-chip"><span>{mission.world.icon}</span><div><small>MISSION {level} · AGES {age}</small><b>{mission.objective}</b><em>{energy} BUILD ENERGY</em></div></div><div className="modal-actions"><button onClick={()=>tutorial?setTutorial(tutorial-1):setScreen("map")}>BACK</button><button className="primary" onClick={()=>tutorial<4?setTutorial(tutorial+1):setScreen("mission")}>{tutorial<4?"NEXT":"ENTER ASSEMBLY BAY"}</button></div></section></main></>}
  if(screen==="mission")return <main className="mission-screen"><header className="mission-top"><button onClick={()=>!launching&&setScreen("map")}>✕</button><div><small>MISSION {level} · {mission.world.name}</small><b>{STAT_INFO[mission.focus].icon} RAISE {STAT_INFO[mission.focus].name.toUpperCase()} TO {mission.target}</b></div><div className="energy"><small>BUILD ENERGY</small><b>⚡ {energy}</b></div><button onClick={()=>speakFriendly(mission.brief+" Goal: raise "+STAT_INFO[mission.focus].name+" to "+mission.target+", and total flight readiness to "+mission.scoreGoal+". "+mission.tip,.7)}>🔊</button></header><section className="mission-layout"><div><RocketBuilder mission={mission} stats={stats} history={history.map(turn=>turn.part)} launching={launching}/><div className="goal-strip"><div className={stats[mission.focus]>=mission.target?"met":""}><span>{STAT_INFO[mission.focus].icon}</span><p><small>FOCUS GOAL</small><b>{stats[mission.focus]} / {mission.target}</b></p></div><div className={readinessScore(stats)>=mission.scoreGoal?"met":""}><span>🚀</span><p><small>TOTAL READINESS</small><b>{readinessScore(stats)} / {mission.scoreGoal}</b></p></div><button onClick={undo} disabled={!history.length||launching}>↶ UNDO</button><button onClick={reset} disabled={launching}>↻ RESET</button></div></div><article className="project-tray"><p className="eyebrow">SPACECRAFT SYSTEMS</p><h2>{mission.objective}</h2><p>{mission.brief}</p><div className="action-grid">{parts.map(part=><button key={part.id} disabled={part.cost>energy||ready||launching} onClick={()=>addPart(part)}><span>{part.icon}</span><div><small>{part.category}</small><b>{part.name}</b><em>{Object.entries(part.effects).map(([key,value])=>"+"+value+" "+STAT_INFO[key as keyof typeof STAT_INFO].name).join(" · ")}</em></div><strong>⚡{part.cost}</strong></button>)}</div>{message&&<div className="science-fact"><span>💡</span><p><b>MISSION NOTE</b>{message}</p></div>}{ready?<button className="finish launch-button" onClick={launch} disabled={launching}>{launching?"3 · 2 · 1 · LIFTOFF":"START COUNTDOWN · LAUNCH"}</button>:energy===0?<button className="finish reset" onClick={reset}>ENERGY USED · RESET AND REBUILD</button>:<div className="coach"><b>FLIGHT DIRECTOR</b><p>{mission.tip}</p></div>}</article></section></main>;
  if(screen==="result")return <><Topbar save={save} setScreen={setScreen}/><main className="modal-screen"><section className="modal result"><div className="award">🚀</div><p className="eyebrow">MISSION {level} COMPLETE</p><h2>FLIGHT SUCCESS!</h2><p>Your spacecraft met its objective with balanced propulsion, energy, control, and mission systems.</p><div className="result-stars">{"★".repeat(earned.stars)}{"☆".repeat(3-earned.stars)}</div><div className="earned"><div><b>+{earned.xp}</b><small>XP</small></div><div><b>{save.progress[age]}/30</b><small>OPEN</small></div><div><b>{save.badges.length}</b><small>BADGES</small></div></div><div className="modal-actions"><button onClick={()=>setScreen("map")}>STAR MAP</button><button className="primary" onClick={()=>begin(Math.min(30,level+1))}>NEXT MISSION</button></div></section></main></>;
  if(screen==="guide")return <><Topbar save={save} setScreen={setScreen}/><main className="content"><div className="heading"><div><p className="eyebrow">SPACECRAFT FIELD GUIDE</p><h2>SYSTEMS AND SCIENCE</h2><p>Learn how each rocket system helps a real mission work.</p></div><button onClick={()=>setScreen("home")}>HOME</button></div><section className="guide-grid">{ROCKET_PARTS.map(part=><article key={part.id}><span>{part.icon}</span><small>{part.category} · AGES {part.minAge}+</small><h3>{part.name}</h3><p>{part.fact}</p><button onClick={()=>speakFriendly(part.name+". "+part.fact,.7)}>🔊 READ</button></article>)}</section></main></>;
  if(screen==="grownup")return <><Topbar save={save} setScreen={setScreen}/><main className="content"><div className="heading"><div><p className="eyebrow">PRIVATE DEVICE-ONLY SUMMARY</p><h2>GROWN-UP PROGRESS</h2><p>No accounts, advertisements, microphone, camera, location data, or personal information are used.</p></div><button onClick={()=>setScreen("home")}>HOME</button></div><section className="summary"><div><b>{totalStars}</b><small>TOTAL STARS</small></div><div><b>{save.xp}</b><small>FLIGHT XP</small></div><div><b>{FLIGHT_SUMMARY.parts}</b><small>SPACE SYSTEMS</small></div></section><section className="path-progress">{AGES.map(item=><article key={item.age} style={{"--accent":item.color} as CSSProperties}><span>{item.icon}</span><div><small>AGES {item.age}</small><h3>{item.name}</h3><p>{item.detail}</p><div className="bar"><i style={{width:((save.progress[item.age]-1)/30*100)+"%"}}/></div><b>{save.progress[item.age]-1} OF 30 COMPLETE</b></div></article>)}</section><div className="privacy-note"><span>✓</span><p>Parents can help children compare two rocket plans, ask which force or system matters next, count down together, and read the mission facts aloud. Every mission supports unlimited rebuilding.</p></div></main></>;
  return <><Topbar save={save} setScreen={setScreen}/>{screen==="home"&&<main className="home"><section className="home-copy"><p className="eyebrow">BUILD · LAUNCH · EXPLORE</p><h1>SPACEFLIGHT<br/><span>ACADEMY</span></h1><p>Design spacecraft, solve mission tradeoffs, and launch across thirty adventures from Earth to the outer worlds.</p><div className="home-actions"><button className="primary" onClick={()=>setScreen("map")}>OPEN STAR MAP</button><button onClick={()=>setScreen("guide")}>SYSTEMS GUIDE</button></div><div className="current-path"><span>{AGES.find(item=>item.age===age)?.icon}</span><div><small>CURRENT CREW · AGES {age}</small><b>{AGES.find(item=>item.age===age)?.name}</b></div><button onClick={()=>setSave(current=>({...current,age:null}))}>CHANGE</button></div></section><section className="planet-art space-hero"><div className="planet">🚀<i>🌍</i><i>🌙</i><i>🪐</i></div><div className="readout"><span>MISSION CONTROL</span><b>FLIGHT READY</b><em>CADETS ONLINE</em></div></section><nav><button onClick={()=>setScreen("map")}>🗺️<span>MISSIONS</span></button><button onClick={()=>setScreen("guide")}>📘<span>SYSTEMS</span></button><button onClick={()=>setScreen("grownup")}>📊<span>GROWN-UP</span></button></nav></main>}
  {screen==="map"&&<main className="content"><div className="heading"><div><p className="eyebrow">30 MISSIONS · AGES {age}</p><h2>SPACEFLIGHT MISSION MAP</h2><p>Complete five missions at each destination to unlock the next frontier.</p></div><button onClick={()=>setScreen("home")}>HOME</button></div><section className="regions">{WORLDS.map((world,zone)=><article key={world.name} style={{"--accent":world.color} as CSSProperties}><div className="region-title"><span>{world.icon}</span><div><small>DESTINATION {zone+1}</small><h3>{world.name}</h3><p>{world.detail}</p></div></div><div className="levels">{Array.from({length:5},(_,index)=>zone*5+index+1).map(item=><button key={item} disabled={item>save.progress[age]} onClick={()=>begin(item)}><b>{item>save.progress[age]?"🔒":item}</b><span>{"★".repeat(save.stars[missionKey(age,item)]||0)}</span></button>)}</div></article>)}</section></main>}</>;
}

