// World preview: ?r=aurora-pines&time=Sunset&weather=Clear&q=medium&x=..&z=..&h=1.7&yaw=..&pitch=..&fov=70&w=1280&hgt=720
import * as THREE from "three";
import { RESERVES, spawnYaw, type ReserveId } from "../../app/game3d/blueprints/reserves.ts";
import { QUALITY, type QualityName } from "../../app/game3d/render/quality.ts";
import { World } from "../../app/game3d/world/world.ts";
import type { TimeKey, WeatherKey } from "../../app/game3d/world/environment.ts";

const q = new URLSearchParams(location.search);
const W = Number(q.get("w") ?? 1280), H = Number(q.get("hgt") ?? 720);
const rid = (q.get("r") ?? "aurora-pines") as ReserveId;
const def = RESERVES[rid];
const quality = QUALITY[(q.get("q") ?? "medium") as QualityName];
const canvas = document.getElementById("c") as HTMLCanvasElement;
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, preserveDrawingBuffer: true });
renderer.setPixelRatio(1); renderer.setSize(W, H, false);
canvas.style.width = W + "px"; canvas.style.height = H + "px";
renderer.outputColorSpace = THREE.SRGBColorSpace;
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.shadowMap.enabled = quality.shadows;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;
const t0 = performance.now();
const world = new World(renderer, { reserve: def, time: (q.get("time") ?? "Morning") as TimeKey, weather: (q.get("weather") ?? "Clear") as WeatherKey }, quality);
const tBuild = performance.now() - t0;
const cam = new THREE.PerspectiveCamera(Number(q.get("fov") ?? 70), W / H, 0.15, 5000);
const x = Number(q.get("x") ?? def.spawn.x), z = Number(q.get("z") ?? def.spawn.z);
const yaw = Number(q.get("yaw") ?? spawnYaw(def)), pitch = Number(q.get("pitch") ?? -0.03);
cam.position.set(x, world.heightAt(x, z) + Number(q.get("h") ?? 1.7), z);
cam.rotation.order = "YXZ"; cam.rotation.set(pitch, yaw, 0);
cam.updateMatrixWorld();
const player = cam.position.clone(); player.y -= 1.6;
for (let i = 0; i < 30; i++) world.update(1 / 30, cam, player);
renderer.toneMappingExposure = world.env.exposure;
const t1 = performance.now();
renderer.render(world.scene, cam);
const t2 = performance.now();
renderer.render(world.scene, cam);
const info = renderer.info.render;
document.getElementById("info")!.textContent = `${def.name} · build ${tBuild.toFixed(0)} ms · frame ${(performance.now() - t2).toFixed(0)} ms (first ${(t2 - t1).toFixed(0)}) · calls ${info.calls} · tris ${(info.triangles / 1000).toFixed(0)}k · plants ${world.plants.length} · ${world.env.clockString()} sun ${world.env.sunElev.toFixed(1)}°`;
(window as unknown as { __ready: boolean }).__ready = true;
