import assert from "node:assert/strict";
const classList={add(){},remove(){},toggle(){}};
const el=()=>({classList,style:{setProperty(){}},dataset:{},textContent:""});
globalThis.window={devicePixelRatio:1,addEventListener(){},visualViewport:{addEventListener(){}},matchMedia:()=>({matches:true})};
globalThis.document={getElementById:()=>el()};
globalThis.requestAnimationFrame=()=>0;
const {RiftCommandGame}=await import("../app/game.js");
const canvas={width:0,height:0,getBoundingClientRect:()=>({width:844,height:390}),getContext:()=>({})};
const audio=new Proxy({}, {get:()=>()=>{}});
const game=new RiftCommandGame(canvas,audio,{});
game.start(5,{damage:2,armor:2,squad:2});
const roles=new Set(game.squad.map(d=>d.role));
assert.deepEqual([...roles].sort(),["bulwark","medic","rail","striker"].sort());
const types=new Set(game.enemies.map(e=>e.type));
assert.ok(types.has("charger"),"sector 5 should include chargers");
assert.ok(types.has("shield") || types.has("jammer") || types.has("splitter"),"sector 5 should include elite Legion roles");
assert.equal(game.stance,"balanced");
game.cycleStance(); assert.equal(game.stance,"assault");
game.cycleStance(); assert.equal(game.stance,"bulwark");
game.cycleStance(); assert.equal(game.stance,"balanced");
const split=game.createEnemy("splitter",game.player.x,game.player.y+100); split.active=true; game.enemies.push(split);
const before=game.enemies.length; game.damageEnemy(split,99999,true); assert.ok(game.enemies.length>=before+2,"splitter should create two fast shards");
const boss=game.createEnemy("boss",0,100); boss.active=true; boss.bossName="TEST GUARDIAN"; game.enemies.push(boss);
boss.hp=boss.maxHp*.6; const phaseBefore=game.enemies.length; game.updateBossPhase(boss); assert.equal(boss.phaseStage,1); assert.ok(game.enemies.length>=phaseBefore+4);
boss.hp=boss.maxHp*.3; const phase2Before=game.enemies.length; game.updateBossPhase(boss); assert.equal(boss.phaseStage,2); assert.ok(game.enemies.length>=phase2Before+6);
const medic=game.squad.find(d=>d.role==="medic"); assert.ok(medic); game.player.hp-=20; game.medicClock=0; game.updateSquad(.016); assert.ok(game.player.hp>game.player.maxHp-20,"medic should repair a damaged unit");
console.log(`Tactical smoke passed: ${game.squad.length} specialists, ${types.size} sector-5 enemy roles, three formations, splitter reinforcements, two boss phase transitions, medic repair.`);
