// Measures every blueprint's reference build and writes the `overall`
// dimensions table the blueprints, Studio title blocks and conformance test use.
//   node --experimental-strip-types tools/dev/sync-overall.mjs          (report drift)
//   node --experimental-strip-types tools/dev/sync-overall.mjs --write  (regenerate blueprints/overall.ts)
import { writeFileSync } from "node:fs";
import { measureAll } from "./measure.ts";
import { OVERALL } from "../../app/game3d/blueprints/overall.ts";

const write = process.argv.includes("--write");
const rows = measureAll();
let drift = 0;
for (const r of rows) {
  const o = OVERALL[r.id];
  const d = o ? Math.max(Math.abs(o.length - r.length), Math.abs(o.width - r.width), Math.abs(o.height - r.height)) : Infinity;
  if (d > 0.015) { drift++; console.log(`${r.id.padEnd(22)} built L ${r.length.toFixed(3)} W ${r.width.toFixed(3)} H ${r.height.toFixed(3)}  table ${o ? `${o.length} ${o.width} ${o.height}` : "—"}`); }
}
if (write) {
  const body = rows.map(r => `  "${r.id}": { length: ${r.length.toFixed(3)}, width: ${r.width.toFixed(3)}, height: ${r.height.toFixed(3)} },`).join("\n");
  writeFileSync(new URL("../../app/game3d/blueprints/overall.ts", import.meta.url), `// GENERATED by tools/dev/sync-overall.mjs — overall dimensions (m) of each blueprint's\n// reference build (bounding box: length = Z, width = X, height = Y). Do not edit by hand.\n\nexport const OVERALL: Record<string, { length: number; width: number; height: number }> = {\n${body}\n};\n`);
  console.log(`wrote overall.ts (${rows.length} blueprints)`);
} else console.log(drift ? `${drift} blueprints drift more than 15 mm — run with --write` : `all ${rows.length} blueprints within 15 mm`);
