/* eslint-disable @typescript-eslint/no-explicit-any,react-hooks/set-state-in-effect */
"use client";
import{useCallback,useEffect,useRef,useState}from"react";
import{FrontierEngine}from"./frontier-engine";
import{SECTORS,SPECIES,UPGRADES,type UpgradeKey}from"./frontier-data";
type Save={unlocked:number;credits:number;stars:Record<number,number>;upgrades:Record<UpgradeKey,number>;trained:boolean;discoveries:string[]};
const fresh:Save={unlocked:1,credits:200,stars:{},upgrades:{rifle:0,armor:0,boots:0,drone:0},trained:false,discoveries:["raptor"]};
const lessons=[
 {icon:"✥",title:"MOVE TO SURVIVE",text:"Use WASD or arrow keys. On mobile, hold the directional pad to move around the frontier arena."},
 {icon:"⌁",title:"AUTO-TARGET SYSTEM",text:"Your pulse drone automatically targets nearby dinosaurs. Press SPACE or FIRE for a stronger manual shot."},
 {icon:"↯",title:"FLUX DASH",text:"Press SHIFT or tap DASH to burst through danger. The circular meter shows when it is ready again."},
 {icon:"◇",title:"COLLECT & EVOLVE",text:"Pick up glowing energy cores, finish the elimination target, and spend rewards on permanent upgrades."}
];
export default function DinoFrontier(){
 const canvas=useRef<HTMLCanvasElement>(null),engine=useRef<FrontierEngine|null>(null);
 const[save,setSave]=useState<Save>(fresh),[loaded,setLoaded]=useState(false),[selected,setSelected]=useState(0),[screen,setScreen]=useState<"base"|"tutorial"|"play"|"complete"|"failed"|"fieldguide">("base"),[step,setStep]=useState(0),[hud,setHud]=useState<any>({health:100,kills:"0/12",cores:0,score:0,combo:0,dash:0,threat:0}),[toast,setToast]=useState<any>(null),[result,setResult]=useState<any>(null);
 const sector=SECTORS[selected];
 useEffect(()=>{try{const raw=localStorage.getItem("dino-frontier-save-v1");if(raw)setSave({...fresh,...JSON.parse(raw)});if("serviceWorker" in navigator)navigator.serviceWorker.register("/sw.js").catch(()=>{})}catch{}setLoaded(true)},[]);
 useEffect(()=>{if(loaded)localStorage.setItem("dino-frontier-save-v1",JSON.stringify(save))},[save,loaded]);
 const message=useCallback((text:string,kind:string)=>{setToast({text,kind});window.setTimeout(()=>setToast(null),1200)},[]),complete=useCallback((v:any)=>{setResult(v);setScreen("complete")},[]),fail=useCallback(()=>setScreen("failed"),[]);
 useEffect(()=>{if(screen!=="play"||!canvas.current)return;const game=new FrontierEngine(canvas.current,sector,save.upgrades,{hud:setHud,message,complete,fail});engine.current=game;return()=>{game.destroy();engine.current=null}},[screen,sector,save.upgrades,message,complete,fail]);
 const launch=()=>{if(save.trained)setScreen("play");else{setStep(0);setScreen("tutorial")}};
 const nextLesson=()=>{if(step<3)setStep(s=>s+1);else{setSave(s=>({...s,trained:true}));setScreen("play")}};
 const claim=()=>{const stars=result.health>74?3:result.health>34?2:1,seen=[...new Set([...save.discoveries,...sector.species,...(sector.boss?[sector.boss]:[])])];setSave(s=>({...s,credits:s.credits+sector.reward+result.cores*15,unlocked:Math.min(10,Math.max(s.unlocked,sector.id+1)),stars:{...s.stars,[sector.id]:Math.max(stars,s.stars[sector.id]||0)},discoveries:seen}));setScreen("base")};
 const buy=(key:UpgradeKey)=>{const level=save.upgrades[key],cost=160*(level+1);if(level>=4||save.credits<cost)return;setSave(s=>({...s,credits:s.credits-cost,upgrades:{...s.upgrades,[key]:level+1}}))};
 const hold=(x:number,z:number)=>engine.current?.setMove(x,z),release=()=>engine.current?.clearMove();
 if(!loaded)return<main className="frontier-loading">CALIBRATING FRONTIER GRID…</main>;
 return <main className={`frontier ${screen}`}>
  {screen==="base"&&<><header><div className="brand"><i>DF</i><span><b>DINO FRONTIER</b><small>SURVIVAL COMMAND</small></span></div><nav><button onClick={()=>setScreen("fieldguide")}>FIELD GUIDE</button><strong>◇ {save.credits}</strong></nav></header>
  <section className="frontier-hero"><div><small>EXOPLANET V-17 // FRONTIER SIGNAL ACTIVE</small><h1>TRACK.<br/><em>DEFEND.</em><br/>EVOLVE.</h1><p>Hold the line against living legends. Master a smart arsenal, recover energy cores, and survive ten escalating dinosaur sectors.</p><button className="primary" onClick={launch}>DEPLOY TO SECTOR {sector.id} →</button></div><article className="threat-card" style={{"--sector":sector.color}as any}><small>CURRENT DEPLOYMENT</small><b>{String(sector.id).padStart(2,"0")}</b><h2>{sector.name}</h2><span>{sector.biome}</span><div><i style={{width:`${sector.threat*10}%`}}/></div><p>THREAT {sector.threat}/10 · {sector.target} TARGETS</p></article></section>
  <section className="command-grid"><div className="sectors"><div className="section-title"><b>FRONTIER SECTORS</b><span>{save.unlocked}/10 ACCESSIBLE</span></div>{SECTORS.map((s,i)=><button key={s.id} disabled={s.id>save.unlocked} className={selected===i?"active":""} onClick={()=>setSelected(i)} style={{"--sector":s.color}as any}><i>{String(s.id).padStart(2,"0")}</i><span><b>{s.name}</b><small>{s.biome} · THREAT {s.threat}</small></span><strong>{s.id>save.unlocked?"LOCKED":`${"★".repeat(save.stars[s.id]||0)}${"☆".repeat(3-(save.stars[s.id]||0))}`}</strong></button>)}</div><aside><div className="briefing"><small>MISSION PROFILE</small><h2>{sector.name}</h2><div className="objectives"><span>ELIMINATE<b>{sector.target}</b></span><span>SPECIES<b>{sector.species.length+(sector.boss?1:0)}</b></span><span>REWARD<b>◇ {sector.reward}</b></span><span>BOSS<b>{sector.boss?"YES":"NO"}</b></span></div></div><div className="upgrade-lab"><small>EVOLUTION LAB</small>{UPGRADES.map(u=>{const level=save.upgrades[u.key],cost=160*(level+1);return<button key={u.key} disabled={level>=4||save.credits<cost} onClick={()=>buy(u.key)}><i style={{color:u.color}}>{u.icon}</i><span><b>{u.name}</b><small>{u.detail}</small></span><strong>{level>=4?"MAX":`◇ ${cost}`}<em>{"●".repeat(level)}{"○".repeat(4-level)}</em></strong></button>})}</div></aside></section></>}
  {screen==="tutorial"&&<div className="overlay"><article className="tutorial"><small>RANGER TRAINING // {step+1} OF 4</small><i>{lessons[step].icon}</i><h2>{lessons[step].title}</h2><p>{lessons[step].text}</p><div className="tutorial-dots">{lessons.map((_,i)=><span key={i} className={i===step?"on":""}/>)}</div><button className="primary" onClick={nextLesson}>{step<3?"NEXT SYSTEM":"BEGIN DEPLOYMENT"} →</button></article></div>}
  {screen==="play"&&<section className="game"><canvas ref={canvas}/><div className="game-hud"><span><small>SECTOR</small><b>{sector.name}</b></span><span><small>TARGETS</small><b>{hud.kills}</b></span><span><small>CORES</small><b>◇ {hud.cores}</b></span><span><small>SCORE</small><b>{hud.score}</b></span></div><div className="wave"><i><em style={{width:`${hud.threat}%`}}/></i><b>WAVE {hud.threat}%</b></div><div className="health"><span>RANGER INTEGRITY</span><i><em style={{width:`${hud.health}%`}}/></i><b>{hud.health}%</b></div>{hud.combo>1&&<div className="combo">×{hud.combo}<small>HUNT CHAIN</small></div>}<div className="mobile-pad"><button className="up" onPointerDown={()=>hold(0,-1)} onPointerUp={release} onPointerLeave={release}>▲</button><button className="left" onPointerDown={()=>hold(-1,0)} onPointerUp={release} onPointerLeave={release}>◀</button><button className="down" onPointerDown={()=>hold(0,1)} onPointerUp={release} onPointerLeave={release}>▼</button><button className="right" onPointerDown={()=>hold(1,0)} onPointerUp={release} onPointerLeave={release}>▶</button></div><div className="action-pad"><button onClick={()=>engine.current?.dash()}><b>↯</b><small>{hud.dash>0?hud.dash.toFixed(1):"DASH"}</small></button><button className="fire" onClick={()=>engine.current?.fire(true)}><b>⌁</b><small>FIRE</small></button></div><div className="desktop-help">WASD MOVE · SPACE FIRE · SHIFT DASH</div>{toast&&<div className={`toast ${toast.kind}`}>{toast.text}</div>}<button className="exit" aria-label="Exit mission" onClick={()=>setScreen("base")}>×</button></section>}
  {screen==="complete"&&<div className="overlay"><article className="tutorial result"><small>SECTOR SECURED</small><i>✦</i><h2>FRONTIER HELD</h2><div className="result-grid"><span>TARGETS<b>{result?.kills}</b></span><span>CORES<b>{result?.cores}</b></span><span>INTEGRITY<b>{result?.health}%</b></span><span>TIME<b>{result?.time}s</b></span></div><p>Command has logged the expedition and released your upgrade credits.</p><button className="primary" onClick={claim}>CLAIM ◇ {sector.reward+result?.cores*15}</button></article></div>}
  {screen==="failed"&&<div className="overlay"><article className="tutorial result"><small>FRONTIER BREACHED</small><i className="danger">!</i><h2>REGROUP, RANGER</h2><p>Keep moving, use Flux Dash before the pack closes in, and invest in armor or rifle systems before redeploying.</p><button className="primary" onClick={()=>setScreen("base")}>RETURN TO COMMAND</button></article></div>}
  {screen==="fieldguide"&&<div className="guide"><header><div className="brand"><i>DF</i><span><b>SPECIES ARCHIVE</b><small>FRONTIER FIELD GUIDE</small></span></div><button onClick={()=>setScreen("base")}>RETURN TO COMMAND</button></header><section><small>DISCOVERY DATABASE</small><h1>Know the frontier</h1><p>Each species has a unique silhouette, glow signature, movement speed, armor, and attack pattern.</p><div className="species-grid">{SPECIES.map(s=>{const seen=save.discoveries.includes(s.key);return<article key={s.key} className={seen?"":"locked"} style={{"--species":s.color}as any}><i>{seen?s.icon:"?"}</i><small>{seen?"DISCOVERED":"UNDISCOVERED"}</small><h2>{seen?s.name:"Unknown Signal"}</h2><p>{seen?s.detail:"Secure more frontier sectors to identify this lifeform."}</p></article>})}</div></section></div>}
 </main>
}
