/* eslint-disable @typescript-eslint/no-explicit-any */
import {Color3,Color4,DirectionalLight,Engine,GlowLayer,HemisphericLight,LinesMesh,Mesh,MeshBuilder,Scene,ShadowGenerator,StandardMaterial,TransformNode,UniversalCamera,Vector3} from "@babylonjs/core";
import type{Sector,Species,UpgradeKey}from"./frontier-data";
import {screenForwardZ}from"./movement-input";
type UpgradeState=Record<UpgradeKey,number>;
type Enemy={node:TransformNode;kind:Species;hp:number;speed:number;damage:number;attack:number;phase:number};
type Pickup={mesh:Mesh;value:number};
type Callbacks={hud:(v:any)=>void;message:(text:string,kind:string)=>void;complete:(v:any)=>void;fail:()=>void};
const COLORS:Record<Species,Color3>={raptor:new Color3(.2,1,.45),spitter:new Color3(.72,1,.08),anky:new Color3(1,.48,.08),trike:new Color3(.08,.75,1),rex:new Color3(1,.05,.16)};
const STATS:Record<Species,{hp:number;speed:number;damage:number;scale:number}>={raptor:{hp:34,speed:4.3,damage:8,scale:.8},spitter:{hp:48,speed:3.5,damage:11,scale:.9},anky:{hp:105,speed:2.1,damage:15,scale:1.15},trike:{hp:135,speed:2.6,damage:19,scale:1.25},rex:{hp:420,speed:2.3,damage:27,scale:1.75}};
function material(scene:Scene,name:string,color:Color3,glow=.1){const m=new StandardMaterial(name,scene);m.diffuseColor=color;m.emissiveColor=color.scale(glow);m.specularColor=Color3.White().scale(.28);return m}
export class FrontierEngine{
 engine:Engine;scene:Scene;camera:UniversalCamera;player:TransformNode;sector:Sector;up:UpgradeState;cb:Callbacks;shadow:ShadowGenerator;enemies:Enemy[]=[];pickups:Pickup[]=[];keys=new Set<string>();touchX=0;touchZ=0;health=100;kills=0;cores=0;score=0;combo=0;spawned=0;spawnClock=0;shotClock=0;dashClock=0;dashTime=0;elapsed=0;finished=false;last=performance.now();
 constructor(canvas:HTMLCanvasElement,sector:Sector,up:UpgradeState,cb:Callbacks){this.sector=sector;this.up=up;this.cb=cb;this.engine=new Engine(canvas,true,{antialias:true,powerPreference:"high-performance"});this.scene=this.createScene();this.shadow=this.createLights();this.player=this.createRanger();this.camera=new UniversalCamera("frontierCam",new Vector3(0,18,-15),this.scene);this.camera.inputs.clear();this.camera.minZ=.1;this.buildWorld();this.bind();this.engine.runRenderLoop(()=>this.update());window.addEventListener("resize",this.resize)}
 resize=()=>this.engine.resize();
 createScene(){const s=new Scene(this.engine);s.clearColor=new Color4(.015,.055,.055,1);s.fogMode=Scene.FOGMODE_EXP2;s.fogDensity=.009;s.fogColor=new Color3(.015,.055,.055);new GlowLayer("bioGlow",s,{blurKernelSize:32}).intensity=.75;return s}
 createLights(){const h=new HemisphericLight("sky",new Vector3(0,1,0),this.scene);h.intensity=.9;h.groundColor=new Color3(.05,.12,.08);const d=new DirectionalLight("sun",new Vector3(-.4,-1,.3),this.scene);d.position=new Vector3(16,28,-12);d.intensity=1.45;const sh=new ShadowGenerator(1024,d);sh.useBlurExponentialShadowMap=true;return sh}
 createRanger(){const root=new TransformNode("ranger",this.scene),armor=material(this.scene,"rangerArmor",new Color3(.02,.65,.72),.55),dark=material(this.scene,"rangerSuit",new Color3(.025,.045,.055)),amber=material(this.scene,"rangerLight",new Color3(1,.45,.05),.9);const torso=MeshBuilder.CreateCapsule("rangerTorso",{height:1.4,radius:.34,tessellation:14},this.scene);torso.parent=root;torso.position.y=1.25;torso.material=dark;const chest=MeshBuilder.CreateBox("rangerChest",{width:.75,height:.55,depth:.42},this.scene);chest.parent=root;chest.position.set(0,1.48,.05);chest.material=armor;const head=MeshBuilder.CreateSphere("rangerHelmet",{diameter:.55,segments:14},this.scene);head.parent=root;head.position.y=2.12;head.material=dark;const visor=MeshBuilder.CreateBox("rangerVisor",{width:.45,height:.13,depth:.31},this.scene);visor.parent=root;visor.position.set(0,2.15,.25);visor.material=amber;for(const s of[-1,1]){const leg=MeshBuilder.CreateCapsule(`rangerLeg${s}`,{height:1.05,radius:.14},this.scene);leg.parent=root;leg.position.set(s*.2,.52,0);leg.material=dark;const arm=MeshBuilder.CreateCapsule(`rangerArm${s}`,{height:.92,radius:.11},this.scene);arm.parent=root;arm.position.set(s*.48,1.37,.1);arm.rotation.z=s*.25;arm.material=armor}const rifle=MeshBuilder.CreateBox("arcRifle",{width:.14,height:.16,depth:1.5},this.scene);rifle.parent=root;rifle.position.set(.52,1.35,.5);rifle.material=amber;root.getChildMeshes().forEach(m=>this.shadow.addShadowCaster(m));return root}
 buildWorld(){const ground=MeshBuilder.CreateGround("frontierGround",{width:48,height:48,subdivisions:2},this.scene);ground.material=material(this.scene,"ground",new Color3(.035,.16,.11));ground.receiveShadows=true;const ring=MeshBuilder.CreateTorus("safeRing",{diameter:42,thickness:.12,tessellation:72},this.scene);ring.rotation.x=Math.PI/2;ring.position.y=.06;ring.material=material(this.scene,"ring",new Color3(.08,.95,.85),.9);for(let i=0;i<42;i++){const a=Math.random()*Math.PI*2,r=11+Math.random()*11,x=Math.cos(a)*r,z=Math.sin(a)*r;if(i%3===0){const rock=MeshBuilder.CreatePolyhedron(`rock${i}`,{type:1,size:.7+Math.random()*1.1},this.scene);rock.position.set(x,.45,z);rock.scaling.y=.65;rock.material=material(this.scene,`rockMat${i}`,new Color3(.12,.18,.17))}else{const trunk=MeshBuilder.CreateCylinder(`trunk${i}`,{height:2.8+Math.random()*2,diameter:.22},this.scene);trunk.position.set(x,1.4,z);trunk.material=material(this.scene,`trunkMat${i}`,new Color3(.14,.065,.03));const crown=MeshBuilder.CreateCylinder(`fern${i}`,{height:2.6,diameterTop:0,diameterBottom:2.1,tessellation:7},this.scene);crown.position.set(x,3.2,z);crown.material=material(this.scene,`fernMat${i}`,i%2?new Color3(.05,.48,.24):new Color3(.08,.3,.42),.22)}}}
 createDino(kind:Species){const st=STATS[kind],root=new TransformNode(`${kind}-${this.spawned}`,this.scene),base=COLORS[kind],skin=material(this.scene,`${kind}Skin${this.spawned}`,base,.18),dark=material(this.scene,`${kind}Dark${this.spawned}`,base.scale(.28),.08),bright=material(this.scene,`${kind}Glow${this.spawned}`,base,.85);const body=MeshBuilder.CreateCapsule(`${kind}Body`,{height:2.5,radius:.62,tessellation:12},this.scene);body.parent=root;body.rotation.x=Math.PI/2;body.position.y=1.2;body.material=skin;const head=MeshBuilder.CreateBox(`${kind}Head`,{width:.8,height:.62,depth:1.05},this.scene);head.parent=root;head.position.set(0,1.55,1.6);head.material=skin;const jaw=MeshBuilder.CreateBox(`${kind}Jaw`,{width:.7,height:.24,depth:.9},this.scene);jaw.parent=root;jaw.position.set(0,1.33,1.82);jaw.material=dark;const tail=MeshBuilder.CreateCylinder(`${kind}Tail`,{height:2.9,diameterTop:.08,diameterBottom:.58,tessellation:10},this.scene);tail.parent=root;tail.rotation.x=Math.PI/2;tail.position.set(0,1.12,-1.85);tail.material=skin;for(const s of[-1,1])for(const z of[-.7,.75]){const leg=MeshBuilder.CreateCapsule(`${kind}Leg${s}${z}`,{height:1.18,radius:.16},this.scene);leg.parent=root;leg.position.set(s*.48,.55,z);leg.material=dark}if(kind==="raptor"){for(let i=0;i<5;i++){const feather=MeshBuilder.CreateCylinder(`feather${i}`,{height:.55,diameterTop:0,diameterBottom:.18,tessellation:5},this.scene);feather.parent=root;feather.rotation.x=-.6;feather.position.set(0,1.95,1.2-i*.3);feather.material=bright}}if(kind==="spitter"){const frill=MeshBuilder.CreateTorus("venomFrill",{diameter:1.45,thickness:.18,tessellation:18},this.scene);frill.parent=root;frill.rotation.x=Math.PI/2;frill.position.set(0,1.52,1.05);frill.material=bright}if(kind==="anky"){for(let i=-2;i<=2;i++){const plate=MeshBuilder.CreatePolyhedron(`plate${i}`,{type:1,size:.38},this.scene);plate.parent=root;plate.position.set(0,1.85,i*.5);plate.material=bright}const club=MeshBuilder.CreateSphere("tailClub",{diameter:.85,segments:8},this.scene);club.parent=root;club.position.set(0,1.05,-3.2);club.material=dark}if(kind==="trike"){const frill=MeshBuilder.CreateSphere("shieldFrill",{diameter:1.3,segments:12},this.scene);frill.parent=root;frill.scaling.z=.22;frill.position.set(0,1.72,1.2);frill.material=bright;for(const s of[-1,1]){const horn=MeshBuilder.CreateCylinder(`horn${s}`,{height:1.05,diameterTop:0,diameterBottom:.16,tessellation:8},this.scene);horn.parent=root;horn.rotation.x=Math.PI/2;horn.position.set(s*.34,1.72,2.3);horn.material=dark}}if(kind==="rex"){head.scaling.set(1.3,1.25,1.35);jaw.scaling.set(1.4,1.35,1.4);for(const s of[-1,1]){const brow=MeshBuilder.CreateBox(`rexBrow${s}`,{size:.25},this.scene);brow.parent=root;brow.position.set(s*.35,1.88,2.05);brow.material=bright}}root.scaling.setAll(st.scale);root.getChildMeshes().forEach(m=>this.shadow.addShadowCaster(m));return root}
 spawn(kind?:Species){const pool=this.sector.species,chosen=kind||pool[Math.floor(Math.random()*pool.length)],st=STATS[chosen],a=Math.random()*Math.PI*2,r=19+Math.random()*2,node=this.createDino(chosen);node.position.set(Math.cos(a)*r,0,Math.sin(a)*r);node.rotation.y=Math.atan2(-node.position.x,-node.position.z);this.enemies.push({node,kind:chosen,hp:st.hp*(1+this.sector.threat*.08),speed:st.speed*(1+this.sector.threat*.025),damage:st.damage*(1+this.sector.threat*.04),attack:0,phase:Math.random()*6});this.spawned++}
 bind(){window.addEventListener("keydown",this.down);window.addEventListener("keyup",this.keyup)}
 down=(e:KeyboardEvent)=>{this.keys.add(e.code);if(e.code==="Space"){e.preventDefault();this.fire(true)}if(e.code==="ShiftLeft"||e.code==="ShiftRight")this.dash()};keyup=(e:KeyboardEvent)=>this.keys.delete(e.code);
 setMove(x:number,z:number){this.touchX=x;this.touchZ=z}clearMove(){this.touchX=0;this.touchZ=0}
 dash(){if(this.dashClock<=0){this.dashTime=.55;this.dashClock=Math.max(2.7,5-this.up.boots*.55);this.cb.message("FLUX DASH","good")}}
 nearest(){let best:Enemy|undefined,dist=999;for(const e of this.enemies){const d=Vector3.DistanceSquared(e.node.position,this.player.position);if(d<dist){best=e;dist=d}}return best}
 fire(manual=false){const rate=Math.max(.19,.48-this.up.drone*.055);if(this.shotClock>0&&!manual)return;const e=this.nearest();if(!e)return;const range=12+this.up.rifle*1.7,dist=Vector3.Distance(e.node.position,this.player.position);if(dist>range)return;this.shotClock=manual?rate*.45:rate;this.player.rotation.y=Math.atan2(e.node.position.x-this.player.position.x,e.node.position.z-this.player.position.z);const start=this.player.position.add(new Vector3(.42,1.45,.3)),end=e.node.position.add(new Vector3(0,1.25,0)),beam=MeshBuilder.CreateLines("arcShot",{points:[start,end],updatable:false},this.scene)as LinesMesh;beam.color=manual?new Color3(1,.7,.1):new Color3(.1,1,1);setTimeout(()=>beam.dispose(),75);e.hp-=16+this.up.rifle*6+(manual?5:0);if(e.hp<=0)this.defeat(e)}
 defeat(e:Enemy){const pos=e.node.position.clone(),i=this.enemies.indexOf(e);if(i>=0)this.enemies.splice(i,1);e.node.dispose();this.kills++;this.combo++;this.score+=100+this.combo*18+(e.kind==="rex"?700:0);if(Math.random()<.68||e.kind==="rex")this.drop(pos,e.kind==="rex"?5:1);this.cb.message(e.kind==="rex"?"APEX NEUTRALIZED":"TARGET CLEARED ×"+this.combo,"good")}
 drop(pos:Vector3,value:number){const m=MeshBuilder.CreatePolyhedron("energyCore",{type:1,size:.42},this.scene);m.position=pos.clone();m.position.y=.65;m.material=material(this.scene,"coreGlow"+this.pickups.length,new Color3(.1,1,.85),.95);this.pickups.push({mesh:m,value})}
 update(){const now=performance.now(),dt=Math.min(.04,(now-this.last)/1000);this.last=now;if(this.finished){this.scene.render();return}this.elapsed+=dt;this.spawnClock-=dt;this.shotClock-=dt;this.dashClock-=dt;this.dashTime-=dt;const left=this.keys.has("KeyA")||this.keys.has("ArrowLeft"),right=this.keys.has("KeyD")||this.keys.has("ArrowRight"),up=this.keys.has("KeyW")||this.keys.has("ArrowUp"),down=this.keys.has("KeyS")||this.keys.has("ArrowDown");let mx=(right?1:0)-(left?1:0)+this.touchX,mz=screenForwardZ(up,down,this.touchZ);const len=Math.hypot(mx,mz)||1;mx/=len;mz/=len;const speed=(5.2+this.up.boots*.55)*(this.dashTime>0?2.45:1);this.player.position.x=Math.max(-19,Math.min(19,this.player.position.x+mx*speed*dt));this.player.position.z=Math.max(-19,Math.min(19,this.player.position.z+mz*speed*dt));this.camera.position.set(this.player.position.x*.2,18,this.player.position.z-15);this.camera.setTarget(this.player.position.add(new Vector3(0,0,2)));const cap=3+Math.min(8,Math.floor(this.sector.threat*.7));if(this.spawnClock<=0&&this.spawned<this.sector.target&&this.enemies.length<cap){const finalBoss=this.sector.boss&&this.spawned===this.sector.target-1;this.spawn(finalBoss?this.sector.boss:undefined);this.spawnClock=Math.max(.55,2.1-this.sector.threat*.1)}this.fire();for(const e of[...this.enemies]){const to=this.player.position.subtract(e.node.position),dist=to.length();if(dist>1.6){to.normalize();e.node.position.addInPlace(to.scale(e.speed*dt));e.node.rotation.y=Math.atan2(to.x,to.z);e.node.position.y=Math.sin(this.elapsed*5+e.phase)*.035}else{e.attack-=dt;if(e.attack<=0){e.attack=1.05;const reduction=1-this.up.armor*.12;this.health=Math.max(0,this.health-e.damage*reduction);this.combo=0;this.cb.message(`${e.kind.toUpperCase()} IMPACT`,"warn")}}}for(const p of[...this.pickups]){p.mesh.rotation.y+=dt*3;if(Vector3.DistanceSquared(p.mesh.position,this.player.position)<2.4){this.cores+=p.value;this.score+=p.value*60;p.mesh.dispose();this.pickups.splice(this.pickups.indexOf(p),1);this.cb.message(`ENERGY CORE +${p.value}`,"good")}}if(this.health<=0){this.finished=true;this.cb.fail()}if(this.kills>=this.sector.target&&this.enemies.length===0){this.finished=true;setTimeout(()=>this.cb.complete({kills:this.kills,cores:this.cores,score:this.score,health:Math.round(this.health),time:Math.round(this.elapsed)}),450)}this.cb.hud({health:Math.round(this.health),kills:`${this.kills}/${this.sector.target}`,cores:this.cores,score:this.score,combo:this.combo,dash:Math.max(0,this.dashClock),threat:Math.min(100,Math.round((this.spawned/this.sector.target)*100))});this.scene.render()}
 destroy(){window.removeEventListener("resize",this.resize);window.removeEventListener("keydown",this.down);window.removeEventListener("keyup",this.keyup);this.scene.dispose();this.engine.dispose()}
}
