// Rebuilds app/vendor/three.js from the pinned devDependency.
//   npm install && node tools/vendor-three.mjs
import { build } from "esbuild";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const { version } = JSON.parse(await readFile(resolve(root, "node_modules/three/package.json"), "utf8"));
await build({
  entryPoints: [resolve(root, "tools/three-entry.js")],
  outfile: resolve(root, "app/vendor/three.js"),
  bundle: true,
  format: "esm",
  minify: true,
  target: "es2020",
  legalComments: "none",
  banner: { js: `/* three.js r${version.split(".")[1]} (MIT, Copyright 2010-2026 Three.js Authors) + selected addons. Generated by tools/vendor-three.mjs. */` }
});
console.log(`Vendored three.js ${version} into app/vendor/three.js`);
